version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'yeet'
      MYSQL_DATABASE: 'brb'
